import Header from "@/components/Header";
import "./globals.css";
import "./github-markdown.css";
import "github-markdown-css/github-markdown-dark.css";
import Footer from "@/components/Footer";

export const metadata = {
    title: "ccctw-blog",
    description: "Generated by next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="dark">
            <body className="bg-orange-50 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-300 break-words leading-6 transition-colors duration-500">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
